// Generated by CoffeeScript 1.6.2
(function() {
  $(document).ready(function() {
    return $("#addBtn").on("click", function() {
      var checkBox, deleteImg, listTags, newItem;

      newItem = $("<span>" + $('#addItemTxt').val() + "</span>");
      listTags = $("<li></li>");
      checkBox = $("<input type='checkbox'>");
      deleteImg = $("<button class='deleteBtn'><img class='delete' src='images/remove-icon.png'><span class='btnText'>Remove</span></button>");
      deleteImg.on("click", function() {
        var btn;

        btn = $(this);
        return btn.parent().fadeOut(800, function() {
          return btn.parent().remove();
        });
      });
      checkBox.on("click", function() {
        var chkBox;

        chkBox = $(this);
        if (chkBox.is(':checked')) {
          return chkBox.parent().appendTo('#completedItems').addClass('completed');
        } else {
          return chkBox.parent().appendTo('#todoItems').removeClass('completed');
        }
      });
      $(checkBox).appendTo(listTags);
      $(newItem).appendTo(listTags);
      $(deleteImg).appendTo(listTags);
      $(listTags).appendTo('#todoItems');
      return $('#addItemTxt').val('');
    });
  });

}).call(this);
