// Generated by CoffeeScript 1.6.2
(function() {
  var fastBtn, img, pace, slowBtn, startBtn, stopBtn, walkRight;

  walkRight = function() {
    var width;

    width = document.width - img.width;
    if (parseInt(img.style.left, 10) >= width || pace < 0) {
      return;
    }
    return img.style.left = parseInt(img.style.left, 10) + pace + 'px';
  };

  img = document.getElementById("kittykat");

  pace = 2;

  img.style.position = 'absolute';

  img.style.left = '0px';

  startBtn = document.getElementById('start');

  startBtn.onclick = function() {
    return setInterval(walkRight, 50);
  };

  fastBtn = document.getElementById('faster');

  fastBtn.onclick = function() {
    return pace += 5;
  };

  slowBtn = document.getElementById('slower');

  slowBtn.onclick = function() {
    return pace -= 5;
  };

  stopBtn = document.getElementById('stop');

  stopBtn.onclick = function() {
    return pace = 0;
  };

}).call(this);
